### ISSUE TITLE
doesnt work on intel mac

### ISSUE THREAD

**Issue by kyriejoshua** [AlexOwl/vscode-transparent-color-theme#1]
It's really cool and useful on my m1 mac, but doesnt work on intel mac. Both vscode and vscode insiders.

Please update it for intel mac users. Thanks~

**Comment by marcellobarile** [comment]
That's why it doesn't work :D too bad that is not stated in the readme.

**Comment by AlexOwl** [comment]
@marcellobarile I will include the statement to next release, thanks
